### ISSUE TITLE
Can't create a cluster with c5.2xlarge on AWS

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/sal#6] opened 2024-07-15 13:30 UTC
Using POSTMAN, on AWS EUT,  try to create a cluster with two nodes (master and worker), c5.2xlarge both. Instances are created on AWS but node source fails to be created. 

Environment:
nebulous-cd
proactive job id: 2691
node candidate id: 8a74848890b63b2d0190b66dc96b02ce
cloud id: c9a625c7-f705-4128-948f-6b5765509029

On the same environment, clusters with c5.xlarge work OK.

**Comment by ankicabarisic** [comment] 2024-07-15 13:53
Can you tell me what is the size of the given nodes? Just confirm for me that it 2Gb or more...

**Comment by robert-sanfeliu** [comment] 2024-07-15 13:55
8CPU 16G RAM

**Comment by ankicabarisic** [comment] 2024-07-15 13:59
ok, did you manage to deploy/acquire other nodes for which you are aware they are working fine (just to understand if it is general or specific problem) as i see bunch of failing deployments currently

**Comment by robert-sanfeliu** [comment] 2024-07-15 14:00
yes, I tested with c5.xlarge nodes immediately after and it worked.

**Comment by ankicabarisic** [comment] 2024-07-15 14:03
It looks then much alike this one: https://github.com/eu-nebulous/sal/issues/3
However, as we are doing some improvements on connector-iaas and reporting some problems also directly to JCloud, let's keep it for now blacklisted - and when I have some improvements on this will test again. 

Note that JCloud cause problems for nodes with less of 2Gb and the problem is reported directly to them (however it will take some time to get a new release from them).

Please use this same ticket for the other cases you run into.
Thank you

**Comment by ankicabarisic** [comment] 2024-08-07 08:17
the release for this is committed, check this for details:https://openproject.nebulouscloud.eu/projects/nebulous-2nd-release-1/work_packages/700

**Closed as completed by ankicabarisic** 2024-08-07 08:17 UTC
Labels: bug
